[project]
name = 'stableflow-protocol'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.math-utils]
path = 'contracts/math-utils.clar'
clarity_version = 3
epoch = 3.1

[contracts.security-utils]
path = 'contracts/security-utils.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
